name: Setup
description: Setup toolchain and cache
runs:
  using: composite
  steps: 
    - name: Stable with rustfmt and clippy
      uses: dtolnay/rust-toolchain@stable
    
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-